name: pulse_slab_example
description: A focused Flutter telemetry simulation for the Pulse Slab package.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pulse_slab:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
